# Site settings
title: Aditya Gudibanda
description: A blog about the portfolio and offerings of Aditya Gudibanda
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Aditya Gudibanda
user_description: Machine Learning Researcher, Engineer and Consultant
user_title: Research Engineer
email: adityagudibanda1995@gmail.com
github_username:  hrithikguy
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
